version: 2

models:
  - name: orders
    description: "Table that stores order details."
    columns:
      - name: order_id
        description: "Unique identifier for each order."
      - name: customer_id
        description: "Unique identifier of the customer who placed the order."
      - name: increment_id
        description: "Unique ID used for tracking increments in the order system."
      - name: qtd
        description: "Quantity of items ordered."
      - name: total
        description: "Total value of the order."
      - name: updated_at
        description: "Timestamp of the last update to the order record."

  - name: customers
    description: "Table that stores customer information."
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
      - name: nome
        description: "Name of the customer."
      - name: documento
        description: "Identification document of the customer (e.g., CPF or ID number)."
      - name: cidade
        description: "City where the customer resides."
      - name: estado
        description: "State where the customer resides."
      - name: dt_nascimento
        description: "Date of birth of the customer."
      - name: email
        description: "Email address of the customer."
      - name: updated_at
        description: "Timestamp of the last update to the customer record."

  - name: orders_main
    description: "Table that stores order details."
    columns:
      - name: order_id
        description: "Unique identifier for each order."
      - name: customer_id
        description: "Unique identifier of the customer who placed the order."
      - name: increment_id
        description: "Unique ID used for tracking increments in the order system."
      - name: qtd
        description: "Quantity of items ordered."
      - name: total
        description: "Total value of the order."
      - name: updated_at
        description: "Timestamp of the last update to the order record."

  - name: customers_main
    description: "Table that stores customer information."
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
      - name: nome
        description: "Name of the customer."
      - name: documento
        description: "Identification document of the customer (e.g., CPF or ID number)."
      - name: cidade
        description: "City where the customer resides."
      - name: estado
        description: "State where the customer resides."
      - name: dt_nascimento
        description: "Date of birth of the customer."
      - name: email
        description: "Email address of the customer."
      - name: updated_at
        description: "Timestamp of the last update to the customer record."
